### ISSUE TITLE
🐛  Characters with accented names not detected as the character token

### ISSUE THREAD

**Issue by arussbach** [chuangcaleb/obsidian-fountain-editor#28]
### Describe the bug

If a characher has an accent in their name, it is not detected as a character.

### What's the expected result?

If a character's name is written in cap locks, but contains an accent (ex: ÉTIENNE), it will not be centered as well as the subsequent dialogue.

### Steps to reproduce the behavior

write :

ÉTIENNE
Hello, my name is Étienne.

and you will see the problem.

### Fountain Editor - Plugin Version

v1.1.1

### Obsidian Version

v1.5.3

### What environment are you seeing the problem on?

- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by chuangcaleb** [comment]
Hi! This should be because of the regex selector only simply selecting regular alphabetical characters, not accounting for accented letters — just like you diagnosed in your discord message to me. 

Yeah yeah, I'll work on this soon! Thanks for opening the bug ticket!

**Comment by chuangcaleb** [comment]
Extended the regex for Fountain's "character" token to the "capital" letters in the [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement) Unicode block. This should be enough. 

Take note that the `×` (00D7, or `&#215;`) unicode character is _technically_ included in the unicode range, so it's recognized as a capital letter, but it's too much regex work to exclude it, so meh.

If we need to extend to the capital letters of the Latin-extended blocks (A, B, whatever), those are much more complicated, please comment below on your requirements. If not, please mark this ticket as closed (I'm not sure if you can? or just comment that it works, then I'll close it myself)

<img width="1440" alt="SCR-20240125-kxkw" src="https://github.com/chuangcaleb/obsidian-fountain-editor/assets/62867911/cb14e3d7-7fd9-4656-ba99-fa93fca06a56">

**Comment by arussbach** [comment]
Oh! Great, thanks so much, it works perfectly for all my use casses!
