### ISSUE TITLE
🐛 Courier Prime font used for regular markdown text

### ISSUE THREAD

**Issue by asterox** [chuangcaleb/obsidian-fountain-editor#38]
### Describe the bug

In the sample image on the GitHub page, the "regular" markdown text (not fountain syntax) is shown in default font while the fountain text is in courier.

In my file, all body text is rendered in courier.

### What's the expected result?

Expect body text that is not fountain syntax to be rendered in default font.

### Steps to reproduce the behavior

no special steps needed.

### What environment are you seeing the problem on?

- [X] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by chuangcaleb** [comment]
Hello, can you attach a screenshot of this behaviour? 

You may be looking for Fountain's Synopsis token, starting a line with `=`, which causes the rest of the line to not be processed for Fountain styling. This helps differentiate Synopsis/markdown from Fountain's Action syntax token (if you can call it that, basically the default token if no syntax marker is provided).

**Comment by asterox** [comment]
## Heading 2
Here's a heading in Courier.

EXT. THE FARM
This all seems correct.

JILL
Yep. Looks right.


<img width="697" alt="Screenshot 2024-04-29 at 9 29 38 AM" src="https://github.com/chuangcaleb/obsidian-fountain-editor/assets/418566/b4296c38-8c14-4bb1-a8ab-263671ad3a74">

**Comment by asterox** [comment]
I see. So without the synopsis token it will simply treat text as action.
But Headers are exempt from formatting then?

**Comment by chuangcaleb** [comment]
Based Nord theme user. lol

Yea without the synopsis token, Fountain parsers just assume its action. So I mimicked that. And Headings do not have any implicit styles on them, I don't touch them! :D

**Comment by asterox** [comment]
Understood. Ty!
